name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14.0-rc.2", "pypy-3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Run tests
      run: make coverage
    - name: Static checks
      if: "matrix.python-version == '3.10'"
      run: make requirements check
    - name: Build docs with sphinx
      if: "matrix.python-version == '3.10'"
      run: make docs
    - name: Build packages
      if: "matrix.python-version == '3.10'"
      run: make package
    - name: Upload packages
      if: "matrix.python-version == '3.10'"
      uses: actions/upload-artifact@v4
      with:
        name: more-itertools-packages
        path: dist/*
